spring:
  application:
    name: mvn-metadata-load-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:7000

logging:
  level:
    root: DEBUG